version: '3.7'
services:
  nest-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl --silent --fail localhost:9200/_cat/health?h=st || exit 1'
        ]
      interval: 50s
      timeout: 30s
      retries: 5
    environment:
      - cluster.name=movies-cluster
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - discovery.type=single-node
    ports:
      - 9300:9300
      - 9200:9200
    networks:
      - app-network
  user-server:
    build:
      context: ./
      dockerfile: ./severs/user-server/Dockerfile
    volumes:
      - .:/projects
    ports:
      - 9003:9003
    tty: true
    networks:
      - app-network
  item-server:
    depends_on:
      - nest-elasticsearch
    build:
      context: ./
      dockerfile: ./severs/item-server/Dockerfile
    volumes:
      - .:/projects
    ports:
      - 9001:9001
    tty: true
    networks:
      - app-network
  order-server:
    build:
      context: ./
      dockerfile: ./severs/order-server/Dockerfile
    volumes:
      - .:/projects
    ports:
      - 9002:9002
    tty: true
    networks:
      - app-network
  bff:
    build:
      context: ./
      dockerfile: ./severs/bff/Dockerfile
    volumes:
      - .:/projects
    ports:
      - 9000:9000
    tty: true
    networks:
      - app-network
  client:
    container_name: client
    build:
      context: ./
      dockerfile: ./frontend/client/Dockerfile
    volumes:
      - .:/projects
    ports:
      - 3000:80
    tty: true
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
